### ISSUE TITLE
org.json.JSONException: JSONObject["release_date"] not found.

### ISSUE THREAD

**Issue by Knoxie** [JasonHHouse/Gaps#1]
![image](https://user-images.githubusercontent.com/1057404/52140949-33b8bf80-2622-11e9-9047-f18c5d9c8217.png)

```
org.json.JSONException: JSONObject["release_date"] not found.
	at org.json.JSONObject.get(JSONObject.java:566) ~[json-20180813.jar:na]
	at org.json.JSONObject.getString(JSONObject.java:851) ~[json-20180813.jar:na]
	at com.jasonhhouse.Gaps.GapsApplication.searchForPlexMovie(GapsApplication.java:214) [classes/:na]
	at com.jasonhhouse.Gaps.GapsApplication.run(GapsApplication.java:74) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.jasonhhouse.Gaps.GapsApplication.main(GapsApplication.java:68) [classes/:na]
```

**Comment by JasonHHouse** [comment]
Fixed

**Comment by JourneyOver** [comment]
@JasonHHouse 	I'm getting this in the the released version of GAPS for both deadpool 2, and black panther which seem to be the same ones as @Knoxie 	is getting the errors on.

**Comment by JasonHHouse** [comment]
I get the same error. When we dug into it, we think it's an error in the data on TheMovieDB in the returned query. I'm tracking this issue isn't completely resolved, I just handled the error better. I'll keep an eye on it and see if I can find a better fix for it.

**Comment by kmlucy** [comment]
I'm getting the same error on several movies on the latest version as well.
