### ISSUE TITLE
Cannot run newer versions due to some Java version error

### ISSUE THREAD

**Issue by rg9400** [JasonHHouse/gaps#131]
**Describe the bug**
When I try to run newer versions of GAPS, I get the below error. It seems to be indicating I have an older version of Java, but I just updated it to the latest version, see below versions. I don't know enough about Java to know what's going wrong here

java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

 The last functioning version of GAPS for me was v0.3.1 which works perfectly. Anything after that gives me this issue. 

```
This file was compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**To Reproduce**
1. Install latest Java version from Oracle
2. Try to run any version of GAPS > 0.3.1

**Expected behavior**
GAPS should work with the latest Java

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Gaps Version: v0.4.3

**Comment by JasonHHouse** [comment]
Gaps requires Java 11.  That is the latest LTS release for Java and is backwards compatible with older versions. Oracle and OpenJDK have available downloads. Java 11 gives gaps many features for security and performance that aren't available in 8. You can also run through Docker if you don't want to update or try running with Launch4j and the bundled GapsOnWindows.xml. I'm making some updates to that XML currently to make sure everything works. But those are the three options.

**Comment by rg9400** [comment]
I tried Oracle Java JDK 14.02 as well as AdoptOpenJDK JDK 14.02, JDK 11.08, and JRE 11.08. It didn't seem to work with any of those versions. I would get something similar to the below error using AdoptOpenJDK jdk-11.0.8.10-hotspot and Gaps v0.4.4. The easiest solution is to probably use Docker since I didn't realize how many possible variants of Java exist that are not interchangeable. 

```
2020-07-21 09:14:27.187  WARN 47168 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userDetailsService' defined in class path resource [com/jasonhhouse/gaps/WebSecurityConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.core.userdetails.UserDetailsService]: Factory method 'userDetailsService' threw exception; nested exception is java.lang.NullPointerException
```

**Comment by JasonHHouse** [comment]
I would strongly recommend docker. I don't build for just running the jar anymore, there were too many issues like you're seeing when I first released. If you have trouble with docker, let me know but that should be a much smoother experience.
