### ISSUE TITLE
First time trying to run Gaps on Windows

### ISSUE THREAD

**Issue by waltwhitman6969** [JasonHHouse/gaps#153]
Grabbed the latest Gaps zip (Gaps-0.5.1.zip). Already have the latest Java install (pasted in bold below). 

**java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)**

Extracted the files from the zip. 

Running "java -jar GapsWeb-0.5.1.jar" in cmd line and getting the following error. Googled around a bit to try and figure it out but having no luck.

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jasonhhouse/gaps/GapsApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)`

**Comment by JasonHHouse** [comment]
Gaps requires Java 11 to run, not just Java 8. You can get it from [Oracle](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) or [OpenJDK](https://jdk.java.net/11/). However, the prefered way to run is through docker. If you're on Mac, Linux, or Unraid, it's easy and free to setup. Windows requires the Windows Pro license to run docker, it is still free to download and run docker. If you have a home license, you can use a Linux VM in to run docker. You can use VirtualBox as a free option.

**Comment by JasonHHouse** [comment]
Try this: https://github.com/JasonHHouse/gaps/releases/tag/v0.6.1

**Comment by ronnie138** [comment]
im getting stuck also i downloaded openjdk and downloaded the gap as jar 8.8 and run the start on windows and looks like it working wit loads commands in cmd but i cant get the local host 8484 to work
