### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: 

### ISSUE THREAD

**Issue by Bboy486** [JasonHHouse/gaps#155]
Error
\Gaps>java -jar GapsWeb-0.5.1.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jasonhhouse/gaps/GapsApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

Steps

Installed Prereq's 
Java - https://www.java.com/en/
Jarx - https://bitstorm.org/jarx/

Add Environment Variable

Set JAVA_HOME Environment variable
In “System Properties window” click “Environment Variables…”

Under “System variables” click the “New…” button and enter JAVA_HOME as “Variable name” and the path to your Java JDK directory under “Variable value”

Updated System PATH
1. In “Environment Variables” window under “System variables” select Path
2. Click on “Edit…”
3. In “Edit environment variable” window click “New”
4. Type in  %JAVA_HOME%\bin

Test your configuration
Open a new command prompt and type in:
echo %JAVA_HOME%
java -version

Downloaded Windows GapsWeb-0.5.1.jar
Then go to releases to install Gaps as an exe on Windows. 
GapsOnWindows can be found on the releases page. Gaps-{version}.zip.

Double click GapsWeb-0.5.1.jar to run after associating with jarx.exe

Edit - Sorry meant to put this under bug.

**Comment by JasonHHouse** [comment]
Gaps requires Java 11, not Java 8. That's what the class 52 vs 55 issue is.

**Comment by Bboy486** [comment]
Thank you. I installed a newer java but I have a new error

2020-08-27 15:06:49.781  INFO 10760 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000422: Disabling contextual LOB creation as connection was null
2020-08-27 15:06:51.073  INFO 10760 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-08-27 15:06:52.082 ERROR 10760 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

java.sql.SQLException: path to '/usr/data/gaps.db': 'C:\usr' does not exist
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:215) ~[sqlite-jdbc-3.32.3.2.jar!/:na]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[sqlite-jdbc-3.32.3.2.jar!/:na]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[sqlite-jdbc-3.32.3.2.jar!/:na]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[sqlite-jdbc-3.32.3.2.jar!/:na]
        at org.sqlite.JDBC.createConnection(JDBC.java:115) ~[sqlite-jdbc-3.32.3.2.jar!/:na]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[sqlite-jdbc-3.32.3.2.jar!/:na]

**Comment by JasonHHouse** [comment]
That's a different bug. I did not intend Gaps to run directly in Windows but I can take a look at it. Just a folder issue between Gaps in Docker (linux) vs Windows.

**Comment by JasonHHouse** [comment]
Try this: https://github.com/JasonHHouse/gaps/releases/tag/v0.6.1

**Comment by Bboy486** [comment]
That did it. I messaged you on Reddit with a few minor items. Thanks!

**Comment by JasonHHouse** [comment]
Glad to hear it.
