### ISSUE TITLE
Hostname not verified

### ISSUE THREAD

**Issue by kmlucy** [JasonHHouse/Gaps#23]
I'm getting an error connecting to my Plex server:

```
2019-02-04 14:34:32.955 ERROR 16 --- [           main] com.jasonhhouse.Gaps.GapsApplication     : Error connecting to Plex to get Movie list

javax.net.ssl.SSLPeerUnverifiedException: Hostname <IP ADDRESS> not verified:
    certificate: sha256/OLw8G/2bRkH+g5KpGgWsw9Jy2SVx38Y5GUz8jO/9a9w=
    DN: CN=*.<DOMAIN>.plex.direct, O="Plex, Inc.", L=Los Gatos, ST=California, C=US
    subjectAltNames: [*.<DOMAIN>.plex.direct]
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:330) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.12.1.jar:na]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.12.1.jar:na]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[okhttp-3.12.1.jar:na]
        at okhttp3.RealCall.execute(RealCall.java:92) ~[okhttp-3.12.1.jar:na]
        at com.jasonhhouse.Gaps.GapsApplication.findAllPlexMovies(GapsApplication.java:101) ~[classes/:na]
        at com.jasonhhouse.Gaps.GapsApplication.run(GapsApplication.java:79) ~[classes/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
        at com.jasonhhouse.Gaps.GapsApplication.main(GapsApplication.java:74) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:558) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by JasonHHouse** [comment]
What's the URL you're using?

**Comment by kmlucy** [comment]
I'm using `https://<IP ADDRESS>:32400/library/section
s/1/all?X-Plex-Token=<TOKEN>`

**Comment by JasonHHouse** [comment]
Did you replace the IP address and add in the token? Or is that just a sample?

**Comment by kmlucy** [comment]
I just redacted my IP and token. Other than those two swaps, that is copy/pasted from my run command.

**Comment by JasonHHouse** [comment]
You're trying to hit your plex locally over SSL? If the cert isn't in your jdk trust store, I doubt it will work. Whatever cert you generated you'd have to add over. That's what I'm guessing the issue is.

**Comment by Knoxie** [comment]
Make sure you're using the actual IP and not a hostname. Put in 192.168.0.xxx or w/e your address scheme is for your network.  I ran into this when trying to use my servers hostname.

**Comment by kmlucy** [comment]
Yes, I'm using my actual IP. I also tried my hostname with the same result. I have my Plex set to only allow secure connections, so I will have to temporarily change that if SSL won't work.

**Comment by JasonHHouse** [comment]
SSL works fine, you need to add the key into your JDK trust store if you want to use it. Otherwise, you'd need to turn off SSL in your Plex. It's your Plex rejecting the Java network call.

**Comment by kmlucy** [comment]
I'm just going to temporarily disable required secure connections while I run this.
