### ISSUE TITLE
Error running with Docker

### ISSUE THREAD

**Issue by Kazz3r24** [JasonHHouse/gaps#47]
Please let me know if more information is required.
I attempted to run this using Docker because the Java implementation wasn't working for me either.

`docker run -t -e DBAPIKEY=myapikey -e PLEXADDRESS=http://192.168.0.116:32400/library/sections/1/all/?X-Plex-Token=mytoken -e WRITETOFILE=true -e TMDBLISTID=123450 gaps`

and it returns the following:
`Fatal: Need to specify DB_API_KEY as environment variable
Refer to README.md` 

I did check the readme, there's nothing to be found regarding the environment variable, same with the application.yml. The application.yml file also already contains all the keys it's asking for.

When I attempt to run this with Java:

`java -jar Gaps-0.0.3.jar 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.2.RELEASE)

2019-08-27 13:18:48.422  INFO 143751 --- [           main] com.jasonhhouse.Gaps.GapsApplication     : Starting GapsApplication v0.0.3 on leo with PID 143751 (/opt/Gaps/Gaps-0.0.3.jar started by root in /opt/Gaps)
2019-08-27 13:18:48.426  INFO 143751 --- [           main] com.jasonhhouse.Gaps.GapsApplication     : No active profile set, falling back to default profiles: default
2019-08-27 13:18:49.341  INFO 143751 --- [           main] com.jasonhhouse.Gaps.GapsApplication     : Started GapsApplication in 1.339 seconds (JVM running for 1.801)
2019-08-27 13:18:49.342  INFO 143751 --- [           main] com.jasonhhouse.Gaps.GapsApplication     : Searching for Plex Movies...
2019-08-27 13:18:49.590  INFO 143751 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-08-27 13:18:49.595 ERROR 143751 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.jasonhhouse.Gaps.GapsApplication.main(GapsApplication.java:80) [classes!/:0.0.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Gaps-0.0.3.jar:0.0.3]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Gaps-0.0.3.jar:0.0.3]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [Gaps-0.0.3.jar:0.0.3]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [Gaps-0.0.3.jar:0.0.3]
Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333) ~[okhttp-3.12.1.jar!/:na]
	at okhttp3.HttpUrl.get(HttpUrl.java:916) ~[okhttp-3.12.1.jar!/:na]
	at okhttp3.Request$Builder.url(Request.java:165) ~[okhttp-3.12.1.jar!/:na]
	at com.jasonhhouse.Gaps.GapsApplication.findAllPlexMovies(GapsApplication.java:201) [classes!/:0.0.3]
	at com.jasonhhouse.Gaps.GapsApplication.run(GapsApplication.java:85) [classes!/:0.0.3]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	... 13 common frames omitted
`

I'm happy to provide more information, just let me know what you need!

**Comment by JasonHHouse** [comment]
@Kazz3r24 It's a miss type in the readme. DB_API_KEY is what you need instead of DBAPIKEY

The command should look like this

`docker run -t -e DBAPIKEY=myapikey -e PLEXADDRESS=http://192.168.0.116:32400/library/sections/1/all/?X-Plex-Token=mytoken -e WRITETOFILE=true -e TMDBLISTID=123450 gaps`

All of this will be fixed in a new release coming soon with a thin client website to enter data, but this should fix your problem.
