### ISSUE TITLE
gaps stopped working with v1

### ISSUE THREAD

**Issue by ljmerza** [JasonHHouse/Gaps#90]
i enter the movie db key, then the plex info, and click next and all i get now is :

```
The gap is only getting bigger...
Check the logs to see what went wrong. You can message /u/whitefox111 on Reddit or post an issue on the gaps gaps GitHub if you need more help.
```

there's no way to try again it goes straight to that page now

```
gaps         | 10:00:25.904 [main] INFO org.springframework.core.KotlinDetector - Kotlin reflection implementation not found at runtime, related features won't be available.
gaps         | 
gaps         |   .   ____          _            __ _ _
gaps         |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
gaps         | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
gaps         |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
gaps         |   '  |____| .__|_| |_|_| |_\__, | / / / /
gaps         |  =========|_|==============|___/=/_/_/_/
gaps         |  :: Spring Boot ::        (v2.2.2.RELEASE)
gaps         | 
gaps         | 2020-01-05 10:00:26.705  INFO 1 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Starting GapsApplication v0.1.0 on zoe02 with PID 1 (/usr/app/GapsWeb-0.1.0.jar started by root in /usr/app)
gaps         | 2020-01-05 10:00:26.708  INFO 1 --- [           main] com.jasonhhouse.gaps.GapsApplication     : The following profiles are active: ssl
gaps         | 2020-01-05 10:00:26.818  WARN 1 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
gaps         | 2020-01-05 10:00:28.255  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8484 (https)
gaps         | 2020-01-05 10:00:28.304  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
gaps         | 2020-01-05 10:00:28.305  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.29]
gaps         | 2020-01-05 10:00:28.370  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
gaps         | 2020-01-05 10:00:28.370  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1613 ms
gaps         | 2020-01-05 10:00:28.680  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'clientInboundChannelExecutor'
gaps         | 2020-01-05 10:00:28.686  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'clientOutboundChannelExecutor'
gaps         | 2020-01-05 10:00:28.721  INFO 1 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'messageBrokerTaskScheduler'
gaps         | 2020-01-05 10:00:28.766  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'brokerChannelExecutor'
gaps         | 2020-01-05 10:00:28.868  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService
gaps         | 2020-01-05 10:00:28.869  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'taskExecutor'
gaps         | 2020-01-05 10:00:29.092  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
gaps         | 2020-01-05 10:00:30.165  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
gaps         | 2020-01-05 10:00:30.196  INFO 1 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Starting...
gaps         | 2020-01-05 10:00:30.197  INFO 1 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
gaps         | 2020-01-05 10:00:30.198  INFO 1 --- [           main] o.s.m.s.b.SimpleBrokerMessageHandler     : Started.
gaps         | 2020-01-05 10:00:30.797  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8484 (https) with context path ''
gaps         | 2020-01-05 10:00:30.801  INFO 1 --- [           main] com.jasonhhouse.gaps.GapsApplication     : Started GapsApplication in 4.812 seconds (JVM running for 5.359)
gaps         | 2020-01-05 10:00:31.577  INFO 1 --- [nio-8484-exec-5] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
gaps         | 2020-01-05 10:00:31.578  INFO 1 --- [nio-8484-exec-5] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
gaps         | 2020-01-05 10:00:31.590  INFO 1 --- [nio-8484-exec-5] o.s.web.servlet.DispatcherServlet        : Completed initialization in 12 ms
gaps         | 2020-01-05 10:00:31.631  INFO 1 --- [nio-8484-exec-5] c.j.gaps.controller.GapsController       : getIndex()
gaps         | 2020-01-05 10:00:31.642  WARN 1 --- [nio-8484-exec-5] c.j.gaps.controller.GapsController       : Failed to read gaps properties.
gaps         | 
gaps         | java.io.FileNotFoundException: /usr/data/gaps.properties (No such file or directory)
gaps         |  at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
gaps         |  at java.base/java.io.FileInputStream.open(Unknown Source) ~[na:na]
gaps         |  at java.base/java.io.FileInputStream.<init>(Unknown Source) ~[na:na]
gaps         |  at java.base/java.io.FileReader.<init>(Unknown Source) ~[na:na]
gaps         |  at com.jasonhhouse.gaps.service.IoService.readProperties(IoService.java:282) ~[classes!/:0.1.0]
gaps         |  at com.jasonhhouse.gaps.controller.GapsController.getIndex(GapsController.java:49) ~[classes!/:0.1.0]
gaps         |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
gaps         |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
gaps         |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
gaps         |  at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
gaps         |  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) ~[spring-boot-actuator-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:362) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:72) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
gaps         |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
gaps         |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
gaps         | 
gaps         | 2020-01-05 10:00:31.661  INFO 1 --- [nio-8484-exec-5] c.j.gaps.controller.GapsController       : initBinder()
gaps         | 2020-01-05 10:00:59.941  INFO 1 --- [nio-8484-exec-1] c.j.g.c.PlexConfigurationController      : initBinder()
gaps         | 2020-01-05 10:00:59.944  INFO 1 --- [nio-8484-exec-1] c.j.gaps.controller.GapsController       : validate( PlexSearch{movieDbApiKey='5b713bae92d64cab53739587d0afc801', plexToken='null', address='null', port=null, libraries=[]}, org.springframework.validation.BeanPropertyBindingResult: 0 errors )
gaps         | 2020-01-05 10:00:59.949  INFO 1 --- [nio-8484-exec-1] c.j.g.c.PlexConfigurationController      : postPlexConfiguration( PlexSearch{movieDbApiKey='5b713bae92d64cab53739587d0afc801', plexToken='null', address='null', port=null, libraries=[]} )
gaps         | 2020-01-05 10:00:59.949  INFO 1 --- [nio-8484-exec-1] c.j.gaps.service.GapsServiceImpl         : updatePlexSearch( PlexSearch{movieDbApiKey='5b713bae92d64cab53739587d0afc801', plexToken='null', address='null', port=null, libraries=[]} )
gaps         | 2020-01-05 10:00:59.950  INFO 1 --- [nio-8484-exec-1] c.j.g.c.PlexConfigurationController      : initBinder()
gaps         | 2020-01-05 10:01:09.747  INFO 1 --- [nio-8484-exec-6] c.j.g.c.PlexLibrariesController          : initBinder()
gaps         | 2020-01-05 10:01:09.748  INFO 1 --- [nio-8484-exec-6] c.j.gaps.controller.GapsController       : validate( PlexSearch{movieDbApiKey='null', plexToken='LkF_z7f9sJ9i4gb-RQt6', address='192.168.1.31', port=null, libraries=[]}, org.springframework.validation.BeanPropertyBindingResult: 0 errors )
gaps         | 2020-01-05 10:01:09.752 ERROR 1 --- [nio-8484-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
gaps         | 
gaps         | java.lang.NullPointerException: null
gaps         |  at com.jasonhhouse.gaps.validator.PlexPropertiesValidator.validate(PlexPropertiesValidator.java:44) ~[classes!/:0.1.0]
gaps         |  at org.springframework.validation.DataBinder.validate(DataBinder.java:892) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.validateIfApplicable(ModelAttributeMethodProcessor.java:360) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:162) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:64) ~[spring-webmvc-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) ~[spring-boot-actuator-2.2.2.RELEASE.jar!/:2.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamProcessor.service(StreamProcessor.java:362) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:72) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
gaps         |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
gaps         |  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.29.jar!/:9.0.29]
gaps         |  at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
gaps         | 
gaps         | 2020-01-05 10:01:28.765  INFO 1 --- [MessageBroker-1] o.s.w.s.c.WebSocketMessageBrokerStats    : WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
```

**Comment by Liquidbings** [comment]
Same issues here +1

**Comment by JasonHHouse** [comment]
Tracking looks like the properties file is missing for you. I'll see why it's gone.

**Comment by JasonHHouse** [comment]
`gaps         | 2020-01-05 10:01:09.748  INFO 1 --- [nio-8484-exec-6] c.j.gaps.controller.GapsController       : validate( PlexSearch{movieDbApiKey='null', plexToken='LkF_z7f9sJ9i4gb-RQt6', address='192.168.1.31', port=null, libraries=[]},`

You didn't set a port for the Plex Server. It's null but needs to be a valid port number.

**Comment by ljmerza** [comment]
It said default was 32400 or whatever as if it didn't need to be set if you didn't change it. The problem now is I can't go back without reinstalling.

**Comment by JasonHHouse** [comment]
I don't know what reinstall means. It's a docker container.

**Comment by Knoxie** [comment]
Restarting the Gaps docker or going back to the home page will allow you to redo your Plex settings in the web app. 

Did you install via docker command?

**Comment by ljmerza** [comment]
you have to remove and reup the container. i shouldnt have to do this for every little error. just restarting it doesnt work

**Comment by Knoxie** [comment]
Sorry you're having issues, but you shouldn't have had to reinstall the container.

We're open to feature requests and bug fixes. We're a work in progress.
